### ISSUE TITLE
Forced discharge of the powerwall - better API available?

### ISSUE THREAD

**Issue by fhopley** [696GrocuttT/AppDaemon#1]
Hi,

I saw your project featured on a YouTube video and was interested to hear how you control your Powerwall.  I use the 'Tesla Custom Integration' (along with the 'Tesla HTTP Proxy') to change the Powerwall Operation Mode.  By putting it to Backup with a high backup reserve I can force it to charge from the grid, and in 'Self consumption' mode it matches discharge to home use.  However, my solution for forced discharge is pretty poor - I put it into Time-Based Control and then have high tariffs set in the app for the times when discharge to grid is normally required.  Most of the time this works and force discharges to the grid, but not always - this is particularly a problem when a pricing spike happens at a non peak period of time. 

Do you have a better way to force charge and discharge of the powerwall?  I can enable my energy provider's VPP to control my powerwall and it has forced charge / discharge manual controls which work far better.  They can force charge from the grid at a faster rate, force discharge at any time, and commands of this nature are actioned far quicker.  They must have access to a much more functional API than the 'Tesla Custom Integration' has.

Thanks,

Fred

**Comment by 696GrocuttT** [comment]
I use the https://github.com/696GrocuttT/ha-tesla-gateway integration to control the powerwall. I use a similar approach to you for controlling the powerwall. The main difference is that I extended the ha-tesla-gateway integration to allow me to set the tariff from HA. So I don't have to preset in advance a high tariff value for the times when discharge is normally required. This mostly works but it's not the cleanest solution (if you find a better one let me know). 

As well as forcing the powerwall to change/discharge, it's sometimes useful to put it into standby (eg if its better to run the house off the solar and export everything else when the battery is only part charged). To do this I set a high tariff price and put the powerwall into time-base control (so it wants to discharge), but set the reserve level to the current battery level so it can't discharge. 

There also seams to be some batch processing every 15 minutes going on at Tesla. I don't have any proof of this, but it does fit the behaviour I've seen.  If I change the powerwall settings just after the hour it occasionally doesn't take effect until 15 minutes past the hour. It seams a bit more reliable if I change the settings just before the hour so the new settings get flushed through with the on the hour batch job.
